services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=chat-db
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=user
    ports:
      - 5432:5432
  rabbitmq:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_PASS=secret
      - RABBITMQ_DEFAULT_USER=user
    ports:
      - 5672:5672
