services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=microchat-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432
  rabbitmq:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=secret
    ports:
      - 5672:5672
