#! /usr/bin/bash

# Check for health (Spring Boot Actuator)
curl -s -X GET "$BASE_URL/actuator/health" \
  | jq

# Get messages
curl -s -X GET "$BASE_URL/api/v1/messages/?page=0&count=5" \
  | jq

# Create message
curl -s -X POST "$BASE_URL/api/v1/messages/" \
  -H "Content-Type: application/json" \
  -d '{
    "senderId": 2,
    "content": "Hello, world!"
  }' \
  | jq

# Get moto (For checking dynamic config reload witout service restart)
curl -s -X GET "$BASE_URL/api/v1/messages/moto"
