#!/usr/bin/bash

# Check for health (Spring Boot Actuator)
curl -i -X GET "$MESSAGE_BASE_URL/actuator/health"

# Get messages
curl -i -X GET "$MESSAGE_BASE_URL/api/v1/messages/?page=0&count=5" \
  -u "$CREDENTIALS"

# Create message
curl -i -X POST "$MESSAGE_BASE_URL/api/v1/messages/" \
  -u "$CREDENTIALS" \
  -H "Content-Type: application/json" \
  -d '{
    "senderId": 3,
    "content": "It'\''s a chat btw"
  }'

# Get moto (For checking dynamic config reload witout service restart)
curl -i -X GET "$MESSAGE_BASE_URL/api/v1/messages/moto" \
  -u "$CREDENTIALS"
