#!/usr/bin/bash

# Check for health (Spring Boot Actuator)
curl -i -X GET "$USER_BASE_URL/actuator/health"

# Get all users
curl -i -X GET "$USER_BASE_URL/api/v1/users/" \
  -u "$CREDENTIALS"

# Get user by id
curl -i -X GET "$USER_BASE_URL/api/v1/users/1" \
  -u "$CREDENTIALS"

# Create user
curl -i -X POST "$USER_BASE_URL/api/v1/users/" \
  -u "$CREDENTIALS" \
  -H "Content-Type: application/json" \
  -d '{
    "username": "Andrii",
    "bio": "Just for assistance here"
  }'

# Update user
curl -i -X PUT "$USER_BASE_URL/api/v1/users/1" \
  -u "$CREDENTIALS" \
  -H "Content-Type: application/json" \
  -d '{
    "username": "Mykola",
    "bio": "Is NOT trying to submit the lab on time..."
  }'

# Delete user by id
curl -i -X DELETE "$USER_BASE_URL/api/v1/users/1" \
  -u "$CREDENTIALS"
